# fly.toml app configuration file generated for semu on 2023-09-30T03:12:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "semu"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
