name: Deploy API to Google Cloud

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
      
    - name: Build and Deploy with Maven
      run: mvn clean install appengine:deploy
      working-directory: ./api
