name: Increment Minor Version

on:
  workflow_dispatch:

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Increment minor version
        run: |
          # Extract current version from pom.xml
          VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" api/pom.xml)
          # Get the prefix and the minor version
          PREFIX=$(echo $VERSION | grep -oP '^\d+\.\d+\.')
          MINOR=$(echo $VERSION | grep -oP '(?<=^\d+\.\d+\.)\d+')
          # Increment minor version
          NEW_MINOR=$((MINOR+1))
          # Replace the minor version
          NEW_VERSION="${PREFIX}${NEW_MINOR}-SNAPSHOT"
          # Update pom.xml with the new version
          sed -i "s|<version>${VERSION}</version>|<version>${NEW_VERSION}</version>|g" api/pom.xml
          # Show the updated pom.xml for logging
          cat api/pom.xml
        shell: bash

      - name: Commit changes
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add api/pom.xml
          git commit -m "Increment minor version to ${NEW_VERSION}"
          git push
        env:
          NEW_VERSION: ${{ steps.set-version.outputs.NEW_VERSION }}
        shell: bash
